import { bigIntReplacer, generatePrivate, generatePrivateExcludingIndexes, getPubKeyPoint } from "@tkey/common-types";
import { add0x, bytesToHex } from "@toruslabs/metadata-helpers";
import stringify from "json-stable-stringify";
import { describe, expect, it } from "vitest";

import { AuthMetadata, generateRandomPolynomial, Metadata } from "../src/index";

// Fixtures generated by published @tkey/core@16.0.0 (old version)
// Signatures were produced by elliptic (high-S possible), verified by @noble/curves with lowS:false.
const OLD_FORMAT_FIXTURES = [
  {
    data: {
      pubKey: "03e68acfc0253a10620dff706b0a1b1f1f5833ea3beb3bde2250d5f271f3563606",
      polyIDList: [
        "03e68acfc0253a10620dff706b0a1b1f1f5833ea3beb3bde2250d5f271f3563606|028e329439afba92391a51912d961d54ae18c98a017072aab86c8b429da7b677a3|0x0|1|2|4f26421bbcd236f511c90fb406171b52a5d355caacc2dfdf7911a1e901ed7c40",
      ],
      scopedStore: {},
      generalStore: { something: { test: "oh this is an object" } },
      tkeyStore: {},
      nonce: 0,
      tssKeyTypes: {},
      tssNonces: {},
      tssPolyCommits: {},
      factorPubs: {},
      factorEncs: {},
    },
    sig: "3046022100bdb2a0b5fcce0cce21495dcfb3ab32873e64247911e8bf197dc9c6f1fa99b813022100e3b393e4ff9df798eeb3f27912ff1b5fdaf464617203a7b6c26b9816bb2649a1",
  },
  {
    data: {
      pubKey: "03e68acfc0253a10620dff706b0a1b1f1f5833ea3beb3bde2250d5f271f3563606",
      polyIDList: [
        "03e68acfc0253a10620dff706b0a1b1f1f5833ea3beb3bde2250d5f271f3563606|02ca9b526436f1fa5f28c77c372a8c4185a849e702e938e578098a03039bed4f60|0x0|1|2|7925a32576b1678d09159a24419f54dd441b0468bea80f5d5b75ee7ea8aa82ea",
      ],
      scopedStore: {},
      generalStore: { other: { count: 42 } },
      tkeyStore: {},
      nonce: 1,
      tssKeyTypes: {},
      tssNonces: {},
      tssPolyCommits: {},
      factorPubs: {},
      factorEncs: {},
    },
    sig: "3046022100e031d241cc13d8a899035af6bbc14b07f1aac46d455a61d38893261c9684b8d5022100d95539a0e819a485e03e172cd5cf4e9b375fe8fbdd4483db40027697eedd0e9c",
  },
  {
    data: {
      pubKey: "03e68acfc0253a10620dff706b0a1b1f1f5833ea3beb3bde2250d5f271f3563606",
      polyIDList: [
        "03e68acfc0253a10620dff706b0a1b1f1f5833ea3beb3bde2250d5f271f3563606|02245f5d5404f949a8be4478c98cc7e8555b8d8b6f1f5c38b7203d85d80acf77f4|0x0|1|2|d70f9646f686b2e380258fbb0f36b41c84094362a20519cbae19f6cbed2bd17e",
      ],
      scopedStore: {},
      generalStore: {},
      tkeyStore: {},
      nonce: 0,
      tssKeyTypes: {},
      tssNonces: {},
      tssPolyCommits: {},
      factorPubs: {},
      factorEncs: {},
    },
    sig: "304502210085ab53ec34b1b39d169de83ef2e47a83beade928702a4292d4c6f7f5b656e39b02202d0b3ac8ab18257c64dae1eaffc1f45daab67544537aa61b093458fb6910c7a5",
  },
];

const PRIVATE_KEY = bytesToHex(generatePrivate());

function createTestMetadata(privKeyBN: bigint) {
  const shareIndexes = [1n, 2n];
  shareIndexes.push(generatePrivateExcludingIndexes(shareIndexes));
  const poly = generateRandomPolynomial(1, privKeyBN);
  const shares = poly.generateShares(shareIndexes);
  const metadata = new Metadata(getPubKeyPoint(privKeyBN));
  metadata.addFromPolynomialAndShares(poly, shares);
  metadata.setGeneralStoreDomain("something", { test: "oh this is an object" });
  return metadata;
}

describe("AuthMetadata", function () {
  it("#should authenticate and serialize and deserialize into JSON seamlessly", async function () {
    const privKeyBN = BigInt(`0x${PRIVATE_KEY}`);
    const metadata = createTestMetadata(privKeyBN);
    const a = new AuthMetadata(metadata, privKeyBN);
    const stringified = stringify(a);
    const metadataSerialized = Metadata.fromJSON(JSON.parse(stringify(metadata)));
    const final = AuthMetadata.fromJSON(JSON.parse(stringified));
    expect(final.metadata).toStrictEqual(metadataSerialized);
  });

  it("#should round-trip: stringify -> parse -> fromJSON preserves metadata fields", function () {
    const privKeyBN = BigInt(`0x${PRIVATE_KEY}`);
    const metadata = createTestMetadata(privKeyBN);
    const auth = new AuthMetadata(metadata, privKeyBN);
    const parsed = JSON.parse(stringify(auth, { replacer: bigIntReplacer }));
    const restored = AuthMetadata.fromJSON(parsed);
    expect(restored.metadata.pubKey.x).toStrictEqual(metadata.pubKey.x);
    expect(restored.metadata.pubKey.y).toStrictEqual(metadata.pubKey.y);
    expect(restored.metadata.nonce).toStrictEqual(metadata.nonce);
    expect(restored.metadata.generalStore).toStrictEqual(metadata.generalStore);
  });

  it("#should round-trip multiple times without corruption", function () {
    const privKeyBN = BigInt(`0x${PRIVATE_KEY}`);
    const metadata = createTestMetadata(privKeyBN);

    const auth1 = new AuthMetadata(metadata, privKeyBN);
    const parsed1 = JSON.parse(stringify(auth1, { replacer: bigIntReplacer }));
    const restored1 = AuthMetadata.fromJSON(parsed1);

    const auth2 = new AuthMetadata(restored1.metadata, privKeyBN);
    const parsed2 = JSON.parse(stringify(auth2, { replacer: bigIntReplacer }));
    const restored2 = AuthMetadata.fromJSON(parsed2);

    expect(stringify(restored1.metadata, { replacer: bigIntReplacer })).toStrictEqual(stringify(restored2.metadata, { replacer: bigIntReplacer }));
  });

  it("#should reject tampered signature", function () {
    const privKeyBN = BigInt(`0x${PRIVATE_KEY}`);
    const metadata = createTestMetadata(privKeyBN);
    const auth = new AuthMetadata(metadata, privKeyBN);
    const parsed = JSON.parse(stringify(auth, { replacer: bigIntReplacer }));
    parsed.sig = parsed.sig.slice(0, -2) + "00";
    expect(() => AuthMetadata.fromJSON(parsed)).toThrow(/not valid|invalid/i);
  });

  it("#should reject signature from wrong key", function () {
    const privKeyBN = BigInt(`0x${PRIVATE_KEY}`);
    const otherKey = BigInt(add0x(bytesToHex(generatePrivate())));
    const metadata = createTestMetadata(privKeyBN);
    const auth = new AuthMetadata(metadata, otherKey);
    const parsed = JSON.parse(stringify(auth, { replacer: bigIntReplacer }));
    expect(() => AuthMetadata.fromJSON(parsed)).toThrow(/not valid|invalid/i);
  });

  it("#should throw when toJSON called without privKey", function () {
    const privKeyBN = BigInt(`0x${PRIVATE_KEY}`);
    const metadata = createTestMetadata(privKeyBN);
    const auth = new AuthMetadata(metadata);
    expect(() => auth.toJSON()).toThrow(/privkey unavailable/i);
  });

  it("#should throw when fromJSON called with missing data", function () {
    expect(() => AuthMetadata.fromJSON({})).toThrow(/metadata/i);
    expect(() => AuthMetadata.fromJSON({ data: null })).toThrow(/metadata/i);
  });

  it("#should preserve polyIDList through round-trip", function () {
    const privKeyBN = BigInt(`0x${PRIVATE_KEY}`);
    const metadata = createTestMetadata(privKeyBN);
    const auth = new AuthMetadata(metadata, privKeyBN);
    const parsed = JSON.parse(stringify(auth, { replacer: bigIntReplacer }));
    const restored = AuthMetadata.fromJSON(parsed);
    expect(restored.metadata.polyIDList.length).toStrictEqual(metadata.polyIDList.length);
    for (let i = 0; i < metadata.polyIDList.length; i++) {
      expect(restored.metadata.polyIDList[i][0]).toStrictEqual(metadata.polyIDList[i][0]);
      expect(restored.metadata.polyIDList[i][1].sort()).toStrictEqual(metadata.polyIDList[i][1].sort());
    }
  });

  it("#should be JSON.parse compatible with bigIntReplacer output", function () {
    const privKeyBN = BigInt(`0x${PRIVATE_KEY}`);
    const metadata = createTestMetadata(privKeyBN);
    const auth = new AuthMetadata(metadata, privKeyBN);
    const jsonStr = stringify(auth, { replacer: bigIntReplacer });
    const parsed = JSON.parse(jsonStr);
    const restored = AuthMetadata.fromJSON(parsed);
    expect(restored.metadata.pubKey.x).toStrictEqual(metadata.pubKey.x);
  });

  it("#should load old-format toJSON snapshots via fromJSON (backward compat)", function () {
    for (const fixture of OLD_FORMAT_FIXTURES) {
      const restored = AuthMetadata.fromJSON(fixture);
      const restoredPubKeyHex = bytesToHex(restored.metadata.pubKey.toSEC1(true));
      expect(restoredPubKeyHex).toStrictEqual(fixture.data.pubKey);
      expect(restored.metadata.generalStore).toStrictEqual(fixture.data.generalStore ?? {});
      expect(restored.metadata.nonce).toStrictEqual(fixture.data.nonce ?? 0);
      expect(restored.metadata.polyIDList.length).toBeGreaterThanOrEqual(1);
    }
  });

  it("#should load multiple freshly-generated toJSON outputs via fromJSON", function () {
    const keys: bigint[] = [];
    for (let i = 0; i < 5; i++) {
      keys.push(BigInt(add0x(bytesToHex(generatePrivate()))));
    }

    const snapshots = keys.map((privKeyBN, i) => {
      const shareIndexes = [1n, 2n];
      shareIndexes.push(generatePrivateExcludingIndexes(shareIndexes));
      const poly = generateRandomPolynomial(1, privKeyBN);
      const shares = poly.generateShares(shareIndexes);
      const metadata = new Metadata(getPubKeyPoint(privKeyBN));
      metadata.addFromPolynomialAndShares(poly, shares);
      metadata.setGeneralStoreDomain("counter", { n: i });
      if (i % 2 === 0) metadata.setGeneralStoreDomain("even", { flag: true });
      const auth = new AuthMetadata(metadata, privKeyBN);
      return {
        serialized: JSON.parse(stringify(auth, { replacer: bigIntReplacer })),
        originalPubX: metadata.pubKey.x,
        originalStore: JSON.parse(JSON.stringify(metadata.generalStore)),
      };
    });

    for (let i = 0; i < snapshots.length; i++) {
      const { serialized, originalPubX, originalStore } = snapshots[i];
      const restored = AuthMetadata.fromJSON(serialized);
      expect(restored.metadata.pubKey.x).toStrictEqual(originalPubX);
      expect(restored.metadata.generalStore).toStrictEqual(originalStore);
    }
  });
});
